defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Create Distribution Directory
          command: mkdir -p dist
      - run: 
          name: NPM Install
          command: npm install
      - run: 
          name: NPM Build
          command: npm run build
          environment:
            NODE_ENV: production
      - run: 
          name: Copy and Compress
          command: cd dist/ && tar -cvzf timp.tar.gz ./* && cd ../
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  publish_aws:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Get Pip
          command: curl -O https://bootstrap.pypa.io/get-pip.py
      - run:
          name: Install Pip
          command: python2.7 get-pip.py --user
      - run:
          name: Install AWS CLI
          command: sudo apt-get install python-dev && ~/.local/bin/pip install awscli --upgrade --user
      - run:
          name: Deploy to S3
          command: ~/.local/bin/aws s3 cp ~/repo/dist/timp.tar.gz s3://stukent-timp/timp.tar.gz
  publish_storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys
      - run:
          name: Output Storybook Files
          command: npm run storybook-build
      - run:
          name: Copy to Server
          command: |
            scp -o StrictHostKeyChecking=no -r ~/repo/.storybook-dist/. deploy@storybook.stukent.com:/home/deploy/storybook.stukent.com/public_html
  
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish_aws:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - publish_storybook:
          requires:
            - build
